"""add delivery metrics to answers

Revision ID: 08a66c3f5e44
Revises: 3eb3507512b3
Create Date: 2025-11-04 05:09:28.850366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a66c3f5e44'
down_revision: Union[str, Sequence[str], None] = '3eb3507512b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('eye_contact_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'eye_contact_score')
    # ### end Alembic commands ###
