"""add vocal metrics to answers

Revision ID: 0e8d9d46027d
Revises: ec20f2b37677
Create Date: 2025-11-02 15:18:58.875059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8d9d46027d'
down_revision: Union[str, Sequence[str], None] = 'ec20f2b37677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('speaking_pace_wpm', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('filler_word_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'filler_word_count')
    op.drop_column('answers', 'speaking_pace_wpm')
    # ### end Alembic commands ###
