"""add language support to sessions and questions

Revision ID: 20e26b7a4974
Revises: dd470592eaba
Create Date: 2025-11-11 08:25:32.285175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e26b7a4974'
down_revision: Union[str, Sequence[str], None] = 'dd470592eaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('language_code', sa.String(), server_default='en-US', nullable=False))
    op.add_column('questions', sa.Column('language_code', sa.String(), server_default='en-US', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'language_code')
    op.drop_column('interview_sessions', 'language_code')
    # ### end Alembic commands ###
