"""add raw resume text field

Revision ID: 3eb3507512b3
Revises: e2cfee9834d0
Create Date: 2025-11-04 02:54:52.420738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb3507512b3'
down_revision: Union[str, Sequence[str], None] = 'e2cfee9834d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raw_resume_text')
    # ### end Alembic commands ###
