"""add advanced delivery metrics

Revision ID: 3efb8cad14a7
Revises: 08a66c3f5e44
Create Date: 2025-11-04 14:40:38.004558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efb8cad14a7'
down_revision: Union[str, Sequence[str], None] = '08a66c3f5e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('speaking_pace_wpm', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('filler_word_count', sa.Integer(), nullable=True))
    op.add_column('answers', sa.Column('pitch_variation_score', sa.Float(), nullable=True))
    op.add_column('answers', sa.Column('volume_stability_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'volume_stability_score')
    op.drop_column('answers', 'pitch_variation_score')
    op.drop_column('answers', 'filler_word_count')
    op.drop_column('answers', 'speaking_pace_wpm')
    # ### end Alembic commands ###
