"""feat: add coding interview models

Revision ID: 7ef271b3f4ea
Revises: 8859d75b5452
Create Date: 2025-11-12 16:25:03.847174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ef271b3f4ea'
down_revision: Union[str, Sequence[str], None] = '8859d75b5452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    
    # Add question_type column as nullable first
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE questions SET question_type = 'behavioral' WHERE question_type IS NULL")
    # Now make it NOT NULL
    op.alter_column('questions', 'question_type', nullable=False, server_default='behavioral')
    
    op.add_column('questions', sa.Column('coding_problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'coding_problems', ['coding_problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'coding_problem_id')
    op.drop_column('questions', 'question_type')
    op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
