"""feat: add comprehensive user profile and performance metrics

Revision ID: 8859d75b5452
Revises: 20e26b7a4974
Create Date: 2025-11-12 15:30:30.338801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8859d75b5452'
down_revision: Union[str, Sequence[str], None] = '20e26b7a4974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first, then columns, then table (if they exist)
    from alembic import op
    from sqlalchemy import inspect
    
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check if constraint exists before dropping
    constraints = [c['name'] for c in inspector.get_foreign_keys('questions')]
    if 'questions_coding_problem_id_fkey' in constraints:
        op.drop_constraint(op.f('questions_coding_problem_id_fkey'), 'questions', type_='foreignkey')
    
    # Check if columns exist before dropping
    columns = [c['name'] for c in inspector.get_columns('questions')]
    if 'question_type' in columns:
        op.drop_column('questions', 'question_type')
    if 'coding_problem_id' in columns:
        op.drop_column('questions', 'coding_problem_id')
    
    # Check if table exists before dropping
    tables = inspector.get_table_names()
    if 'coding_problems' in tables:
        indexes = [idx['name'] for idx in inspector.get_indexes('coding_problems')]
        if 'ix_coding_problems_id' in indexes:
            op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
        op.drop_table('coding_problems')
    
    # Add language_code columns if they don't exist
    if 'language_code' not in [c['name'] for c in inspector.get_columns('interview_sessions')]:
        op.add_column('interview_sessions', sa.Column('language_code', sa.String(), server_default='en-US', nullable=False))
    
    if 'session_questions' in [c['name'] for c in inspector.get_columns('interview_sessions')]:
        op.drop_column('interview_sessions', 'session_questions')
    
    if 'language_code' not in [c['name'] for c in inspector.get_columns('questions')]:
        op.add_column('questions', sa.Column('language_code', sa.String(), server_default='en-US', nullable=False))
    
    # Add user profile columns if they don't exist
    user_columns = [c['name'] for c in inspector.get_columns('users')]
    if 'first_name' not in user_columns:
        op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    if 'last_name' not in user_columns:
        op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    if 'primary_goal' not in user_columns:
        op.add_column('users', sa.Column('primary_goal', sa.String(), nullable=True))
    if 'college' not in user_columns:
        op.add_column('users', sa.Column('college', sa.String(), nullable=True))
    if 'degree' not in user_columns:
        op.add_column('users', sa.Column('degree', sa.String(), nullable=True))
    if 'major' not in user_columns:
        op.add_column('users', sa.Column('major', sa.String(), nullable=True))
    if 'graduation_year' not in user_columns:
        op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    if 'skills' not in user_columns:
        op.add_column('users', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    if 'raw_resume_text' not in user_columns:
        op.add_column('users', sa.Column('raw_resume_text', sa.Text(), nullable=True))
    if 'resume_summary' not in user_columns:
        op.add_column('users', sa.Column('resume_summary', sa.Text(), nullable=True))
    if 'resume_score' not in user_columns:
        op.add_column('users', sa.Column('resume_score', sa.Integer(), nullable=True))
    if 'resume_analysis' not in user_columns:
        op.add_column('users', sa.Column('resume_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    if 'role_matches' not in user_columns:
        op.add_column('users', sa.Column('role_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Add answer performance metric columns if they don't exist
    answer_columns = [c['name'] for c in inspector.get_columns('answers')]
    if 'eye_contact_score' not in answer_columns:
        op.add_column('answers', sa.Column('eye_contact_score', sa.Float(), nullable=True))
    if 'pitch_variation_score' not in answer_columns:
        op.add_column('answers', sa.Column('pitch_variation_score', sa.Float(), nullable=True))
    if 'volume_stability_score' not in answer_columns:
        op.add_column('answers', sa.Column('volume_stability_score', sa.Float(), nullable=True))
    if 'posture_stability_score' not in answer_columns:
        op.add_column('answers', sa.Column('posture_stability_score', sa.Float(), nullable=True))
    if 'coding_results' not in answer_columns:
        op.add_column('answers', sa.Column('coding_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('coding_problem_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('question_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('questions_coding_problem_id_fkey'), 'questions', 'coding_problems', ['coding_problem_id'], ['id'])
    op.drop_column('questions', 'language_code')
    op.add_column('interview_sessions', sa.Column('session_questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('interview_sessions', 'language_code')
    op.create_table('coding_problems',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('starter_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('coding_problems_pkey'))
    )
    op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    # ### end Alembic commands ###
