"""add coding problems

Revision ID: 8b1061cd1996
Revises: f1a2b3c4d5e6
Create Date: 2025-11-05 03:49:09.002305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1061cd1996'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_problems_id'), 'coding_problems', ['id'], unique=False)
    op.add_column('answers', sa.Column('coding_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Add question_type column as nullable first
    op.add_column('questions', sa.Column('question_type', sa.String(), nullable=True))
    # Update existing rows to have 'behavioral' as default
    op.execute("UPDATE questions SET question_type = 'behavioral' WHERE question_type IS NULL")
    # Now make it NOT NULL
    op.alter_column('questions', 'question_type', nullable=False)
    
    op.add_column('questions', sa.Column('coding_problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'coding_problems', ['coding_problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'coding_problem_id')
    op.drop_column('questions', 'question_type')
    op.drop_column('answers', 'coding_results')
    op.drop_index(op.f('ix_coding_problems_id'), table_name='coding_problems')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
