"""add user roles table and relationship

Revision ID: dd470592eaba
Revises: 0e8d9d46027d
Create Date: 2025-11-02 15:30:18.391530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd470592eaba'
down_revision: Union[str, Sequence[str], None] = '0e8d9d46027d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create roles table
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    # Insert default roles
    op.execute("INSERT INTO roles (name) VALUES ('user'), ('super_admin')")
    
    # Add role_id column as nullable first
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    
    # Assign default 'user' role to existing users
    op.execute("UPDATE users SET role_id = (SELECT id FROM roles WHERE name = 'user') WHERE role_id IS NULL")
    
    # Now make role_id not nullable
    op.alter_column('users', 'role_id', nullable=False)
    
    # Create foreign key constraint
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
