"""add resume analysis fields

Revision ID: e2cfee9834d0
Revises: 2b9566359264
Create Date: 2025-11-03 18:07:03.913986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2cfee9834d0'
down_revision: Union[str, Sequence[str], None] = '2b9566359264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('resume_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('role_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_matches')
    op.drop_column('users', 'resume_analysis')
    op.drop_column('users', 'resume_score')
    # ### end Alembic commands ###
